### PR TITLE
Sync tier4 universe

### PR DESCRIPTION
**Pull request by yabuta**
## Description

sync main branch. (tier4/universe -> micro-bus)

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s).
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by kenji-miyake** [comment]
Regarding CI files, how about merging #33?
-> Oh, sorry the branch wasn't `main` or `tier4/universe`. Please ignore this.

**Comment by yabuta** [comment]
@kenji-miyake I think it is better to merge this branch after merging https://github.com/tier4/tier4_ad_api_adaptor/pull/33 and merging tier4/universe to this branch.
I think that the PR will resolve some CI problems.

**Comment by isamu-takagi** [comment]
@yabuta I fixed the CI in this [PR](https://github.com/tier4/tier4_ad_api_adaptor/pull/39).

**Comment by yabuta** [comment]
@0x126 I added new change of tier4/universe, so please approve if you OK.

**Review by 0x126 — APPROVED** [review]
OK

**Pull request merged**
