### PR TITLE
feat: add option to ignore set engage request when the status is emergency

### PR DESCRIPTION
**Pull request by tkimura4**
Signed-off-by: tomoya.kimura <tomoya.kimura@tier4.jp>

## PR Type

- New Feature

## Related Links
https://github.com/tier4/autoware_launch/pull/445

## Description
In the current implementation, when a engage request is sent, Autoware will be engaged even if the autoware is in an emergency state.
I added the option to ignore the engage request when the autoware state is an emergency state

## Review Procedure
1. run the planning simulator, and set the vehicle position and goal.

2. set autoware to emergency state
$ros2 service call /api/autoware/set/emergency tier4_external_api_msgs/srv/SetEmergency "{emergency: true}"

3. check that the emergency state is true
$ros2 topic echo /api/autoware/get/emergency

4. call SetOperatorService, and check that the message: `'ignored request because the status is emergency.'` returns.
$ros2 service call /api/autoware/set/operator tier4_external_api_msgs/srv/SetOperator "{mode: {mode: 2}}"

5. check that the engage state remains false
ros2 topic echo /api/autoware/get/engage

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s).
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Review by yukkysaito — APPROVED** [review]
LGTM
@isamu-takagi can you review this?

**Review by isamu-takagi — APPROVED** [review]
I think it's OK to always use false, when is true used? I would like to keep the API options to a minimum.

**Comment by tkimura4** [comment]
@isamu-takagi 
> I think it's OK to always use false

I think so.

@yukkysaito 

Is it OK to set `send_engage_in_emergency` to false as default?

**Comment by yukkysaito** [comment]
> Is it OK to set send_engage_in_emergency to false as default?

It's ok.
cc @0x126 @h-ohta @yn-mrse

**Pull request merged**
