### PR TITLE
change energy level default value for rclpy bug on humble

### PR DESCRIPTION
**Pull request by yabuta**
## PR Type

- Bug Fix

## Description

If subscribing NaN value on humble rclpy(version 3.3.4), rclpy is broken.
So I suggest to change energy level default value to -1.

## Review Procedure
- Execute below code and autoware.
- Initial pose
- Below code is down when default value is NaN, but operate normally when default value is -1.

```py
import rclpy
from rclpy.node import Node
# from std_msgs.msg import String
from tier4_api_msgs.msg import AwapiVehicleStatus


# Nodeクラスを継承
class Listener(Node):
    def __init__(self):
        # 引数node_nameにlistenerを渡す。
        super().__init__("listener")
        
        sub_qos = rclpy.qos.QoSProfile(
            history=rclpy.qos.QoSHistoryPolicy.KEEP_LAST,
            depth=10,
            reliability=rclpy.qos.QoSReliabilityPolicy.BEST_EFFORT,
            durability=rclpy.qos.QoSDurabilityPolicy.SYSTEM_DEFAULT,
        )

        # 引数msg_type、topic_name、callbackに渡してSubscriptionを作成
        # self.create_subscription(String, "chatter", self.callback)
        self.create_subscription(
            AwapiVehicleStatus, "/awapi/vehicle/get/status", self.callback, sub_qos
        )


    # 処理用callback関数
    def callback(self, msg):
        print(msg.data)


def main():
    # RCLの初期化を実行
    rclpy.init()

    # Listenerクラスのコンスタンス化
    node = Listener()

    # ループに入りnode内の処理を実行させる
    rclpy.spin(node)

    # nodeを破壊
    node.destroy_node()

    # RCLをシャットダウン
    rclpy.shutdown()

if __name__ == "__main__":
    main()
```

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s).
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by tkhmy** [comment]
can we merge this PR? As this still will affect in humble

**Comment by isamu-takagi** [comment]
@tkhmy This PR is a draft, but is it actually ready?
@nktener0902 @yabuta Is this change agreed on by FMS/FOA/MOT?

**Comment by tkhmy** [comment]
> @tkhmy This PR is a draft, but is it actually ready? @nktener0902 @yabuta Is this change agreed on by FMS/FOA/MOT?

For software that use python will have an error in inf, so I think we will need it.
I confirmed that FOA will need this change
Related PR: #56

**Review by isamu-takagi — APPROVED** [review]
I found a corresponding ticket for FMS. So I think it is OK.

**Comment by yabuta** [comment]
@isamu-takagi MOT is OK.
FMS is in the process of fix, so I thought it would be a good idea to make it ON REVIEW once that is complete.
@nktener0902 Merging first would not be good because battery = -1 data would be sent before modification, right?

**Comment by nktener0902** [comment]
@yabuta Sorry for late response and thanks for the comment.
FMS will be ready at 26 July. If there are no obstacles, could you merge this PR after that date?

**Comment by yabuta** [comment]
@nktener0902 OK! After FMS release, I will make this PR on-review.

**Comment by yabuta** [comment]
@nktener0902 I think FMS is ready, so can I merge this PR?

**Comment by nktener0902** [comment]
@yabuta Yes, please go ahead !

**Review by nktener0902 — APPROVED** [review]
LGTM

**Pull request merged**
