### PR TITLE
feat: handling invalid lanelet in RTC

### PR DESCRIPTION
**Pull request by ahmeddesokyebrahim**
## PR Type

- New Feature

### Discussion
- [Discussion Link](https://github.com/orgs/autowarefoundation/discussions/3275)
### Issue 
- [Issue Link](https://github.com/autowarefoundation/autoware/issues/3308)
### Relevant PRs
  - [autoware_documentation](https://github.com/autowarefoundation/autoware-documentation/pull/337)
  - [autoware_common](https://github.com/autowarefoundation/autoware_common/pull/175)
  - [tier4/tier4_autoware_msgs](https://github.com/tier4/tier4_autoware_msgs/pull/76) 
  - [autoware_adapi_msgs](https://github.com/autowarefoundation/autoware_adapi_msgs/pull/27)
  - [autoware_launch](https://github.com/autowarefoundation/autoware_launch/pull/235)
  - [autoware_universe](https://github.com/autowarefoundation/autoware.universe/pull/3000)

## Description

This PR is to add the needed code for handling invalid lanelet by RTC
## Review Procedure

For compiling and testing this PR, all PRs in related links section need to be taken into consideration.
:exclamation: **Merge sequence can be found [here](https://github.com/orgs/autowarefoundation/discussions/3275#discussioncomment-5379038)** :exclamation: 

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code follows [coding guidelines][coding-guidelines]
- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s).
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by yukkysaito** [comment]
@isamu-takagi Can you check this PR?

**Comment by isamu-takagi** [comment]
@tkhmy Can you review this PR?

**Comment by tkhmy** [comment]
@ahmeddesokyebrahim 
Hi, based on your use case, the no_drivable_lane should not be approve to drive autonomously. So mean the no_drivable_lane should be keep inactive along the no drivable lane?
Do it have the case that autoware think it is safe and auto active it?

**Comment by ahmeddesokyebrahim** [comment]
Thanks @tkhmy san for your comment.
Actually I was not able to understand your questions. May you please clarify or elaborate more about what you mean ?

**Comment by tkhmy** [comment]
> Thanks @tkhmy san for your comment. Actually I was not able to understand your questions. May you please clarify or elaborate more about what you mean ?

@ahmeddesokyebrahim 
The RTC is used for this purpose, as you can see, it does not publish the stop wall, instead, it let user to handle the stop wall behavior, user can decide whether to stop or go. 
> publish the decision status of behavior planning modules and receive execution command from external of an autonomous driving system.
https://autowarefoundation.github.io/autoware.universe/main/planning/rtc_interface/


In your case, you do not want the no_driving_lane stop wall to be cancel, instead you will want the user to manually drive the vehicle to pass over the no driving area. Or it is okay that user able to cancel the no_driving_lane stop wall and continue drive autonomously?

For the auto_mode, it handle in this [module](https://autowarefoundation.github.io/autoware.universe/main/planning/rtc_auto_mode_manager/), if autoware think the module is safe, and the auto_mode is turn on, it will decide to continue driving in the no_driving_lane

**Comment by ahmeddesokyebrahim** [comment]
Thanks for your clarification @tkhmy san.

In this module case, we want the user to manually drive the vehicle to pass over the `no_driving_lane` and it is not safe to drive autonomously during the `no_driving_lane` (i.e., any autonomous driving request should be cancelled and the vehicle shall stay in its place).

Is my implementation doing it like that or do I need to change anything ?

**Comment by mitsudome-r** [comment]
@isamu-takagi @tkhmy I think the objective here is to just notify the driver to override the vehicle. Were there any interface to do that at the moment? (i.e. request to override)

**Comment by tkhmy** [comment]
> In this module case, we want the user to manually drive the vehicle to pass over the no_driving_lane and it is not safe to drive autonomously during the no_driving_lane (i.e., any autonomous driving request should be cancelled and the vehicle shall stay in its place).
Is my implementation doing it like that or do I need to change anything ?

@ahmeddesokyebrahim I think it can be discuss, but for current RTC, the user can approve the no_driving_lane when the it is show

> I think the objective here is to just notify the Driver to override the vehicle. Were there any interface to do that at the moment? (i.e. request to override)

@mitsudome-r I think there is no interface to show the override, @isamu-takagi how do you think?

**Comment by isamu-takagi** [comment]
@ahmeddesokyebrahim @mitsudome-r @tkhmy 
RTC is only a support function during autonomous driving, and switching to manual driving is not covered. As @tkhmy said, I think this should be implemented as a new API for takeover request/request to intervene (TOR/RTI). This API will be classified as fail-safe.

**Comment by isamu-takagi** [comment]
Created an issue https://github.com/autowarefoundation/autoware/issues/3487 for new API.

**Comment by ahmeddesokyebrahim** [comment]
@mitsudome-r san : Shall I wait for the new API to be implementation and reflect that in the `no_drivable_lane` module. Or can we proceed for now until it is implemented, tested, and merged then we can open a new issue for that on  `no_drivable_lane` module ?

**Comment by ahmeddesokyebrahim** [comment]
As RTC handling has been removed from this feature and this PR is no longer having any files changes, I am closing this PR.

**Pull request closed without merging**
