### PR TITLE
change base64 converter msg type

### PR DESCRIPTION
**Pull request by yabuta**
## PR Type

- Improvement

## Related Links

https://github.com/tier4/pilot-auto.x2/pull/112

## Description

change msg type of base64 converter to String

## Review Procedure

- execute Autoware and play rosbag 
- Check msg type
  - ros2 topic info /api/external/get/base64/image/sensing/camera/camera4/image_raw/compressed

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s).
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by 0x126** [comment]
The code looks good, I hope you check the results of some tests.

**Comment by yabuta** [comment]
@0x126 2021-11-02-11-10-05のGSM8の柏の葉のrosbagでlsimを動かしたところMOTで画像が表示されました

**Comment by 0x126** [comment]
あとはbuild-and-test-differential, pre-commit(optionalじゃない方)あたりはpassしたいです！
(semantic-pull-requestはマージのときに気をつけてくれればOK)

**Review by 0x126 — APPROVED** [review]

**Comment by yabuta** [comment]
@0x126 Approveもらってましたがgithub action通すためにいろいろ変更したので再度確認をお願いします

**Review by 0x126 — APPROVED** [review]

**Pull request merged**
