### PR TITLE
refactor(autoware_auto_control_msgs): replace autoware_auto_control_msgs with autoware_control_msgs

### PR DESCRIPTION
**Pull request by xmfcx**
## PR Type

- Refactor

## Related Links

- https://github.com/autowarefoundation/autoware.universe/issues/3674
- https://github.com/autowarefoundation/autoware.universe/pull/3677
- https://github.com/autowarefoundation/autoware_launch/pull/353
- https://github.com/tier4/pacmod_interface/pull/61

## Description

Replace all usages of

- https://github.com/tier4/autoware_auto_msgs/tree/tier4/main/autoware_auto_control_msgs/msg
with
- https://github.com/autowarefoundation/autoware_msgs/tree/main/autoware_control_msgs/msg

## Review Procedure

Make sure it compiles with the rest of the Autoware once it is merged along with the Autoware Universe PR:
- https://github.com/autowarefoundation/autoware.universe/pull/3677
- https://github.com/tier4/pacmod_interface/pull/61
- https://github.com/autowarefoundation/autoware_launch/pull/353

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [x] Commits are properly organized and messages are according to the guideline
- [x] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s).
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by xmfcx** [comment]
Will need to be merged with
- https://github.com/autowarefoundation/autoware.universe/pull/3677
- https://github.com/tier4/pacmod_interface/pull/61
- https://github.com/autowarefoundation/autoware_launch/pull/353
at the same time.

**Comment by xmfcx** [comment]
@isamu-takagi @mitsudome-r  Hi, could you review this along with https://github.com/autowarefoundation/autoware.universe/pull/3677 if possible?

- I've tested both PRs with [Planning simulation demo](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/) and it works fine.
  - https://github.com/autowarefoundation/autoware.universe/pull/3677#issuecomment-1549706299

**Comment by isamu-takagi** [comment]
@xmfcx I tried it in the planning simulator, but I couldn't press the autonomous mode button. It seems that [topics.yaml in autoware_launch](https://github.com/autowarefoundation/autoware_launch/blob/main/autoware_launch/config/system/component_state_monitor/topics.yaml) also needs to be changed.

**Review by isamu-takagi — APPROVED** [review]
After fixing the topics.yaml in autoware_launch, it worked fine. There is no problem as a change in this repository, so I approved it. Please synchronize the timing of other repository merges.

**Comment by xmfcx** [comment]
> @xmfcx I tried it in the planning simulator, but I couldn't press the autonomous mode button. It seems that [topics.yaml in autoware_launch](https://github.com/autowarefoundation/autoware_launch/blob/main/autoware_launch/config/system/component_state_monitor/topics.yaml) also needs to be changed.

Thanks a lot for finding it out. I've fixed it too but didn't realize and push it as a PR.

Since I was refactoring multiple repositories across Autoware at once, I used `vcs pull src` to help me find if I forgot pushing a repository.
But it was a bad idea. Now I use `vcs status src` and It shows me the things I forgot pushing.

I need to push my changes on `src/vehicle/external/pacmod_interface` too.

**Comment by xmfcx** [comment]
I'm closing all of my message migration PRs.

**Pull request closed without merging**
