### PR TITLE
fix: rtc distance

### PR DESCRIPTION
**Pull request by Hidenaga41**
## PR Type

- Bug Fix

## Related Links

[bug of rclpy](https://github.com/ros2/rclpy/issues/848)

## Description
If subscribing NaN value on humble rclpy(version 3.3.4), rclpy is broken.
Therefore, a change was added to include the value -100000 as a temporary change when -inf or NaN values were included in Distance.

1.  rtc intersections
2. ros2 topic echo /api/external/get/rtc_status | grep distance
3. make sure output from ros2 topic echo exist 

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s).
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Review by tkhmy — APPROVED** [review]
LGTM

**Comment by yabuta** [comment]
@tkhmy Do you know that FOA RTC works with this PR?

**Comment by tkhmy** [comment]
> @tkhmy Do you know that FOA RTC works with this PR?

@yabuta Yes, is working fine

**Review by yabuta — APPROVED** [review]
LGTM

**Comment by Hidenaga41** [comment]
ありがとうございます。マージします。

**Pull request merged**
