### PR TITLE
feat: add external api adaptor for calibration status

### PR DESCRIPTION
**Pull request by TakumiKozaka-T4**
## PR Type

- New Feature

## Related Links

https://github.com/autowarefoundation/autoware.universe/pull/722

## Description

Add external api adapter for calibration data related to the linked PR.
This adapter provides the following items.
- ROS Topic :  /api/external/get/calibration_status
 Calibration status (currently only accel_brake_map calibration status is included)
- ROS Service : /api/external/get/accel_brake_map_calibrator/data
  This returns plot and new accel brake map suggested by autoware

## Review Procedure

Test for calibration status
Open three terminal and run the following.
- Terminal 1 : Run planning simulator
- Terminal 2 : Launch accel_brake_map_calibrator
- Terminal 3 : `ros2 topic echo /api/external/get/calibration_status`

Calibration status will be published as follows.
>stamp:
>  sec: 1653529613
>  nanosec: 71053510
>status_array:
>  target: 1
>  status: 0

Test for the server
Open two terminal and run the following.

- Terminal for server : ros2 run accel_brake_map_calibrator plot_csv_server_node.py
  "plot.svg" should be created in the directory you run the server.
- Terminal for client : ros2 run accel_brake_map_calibrator plot_csv_server_node.py
  The directory "test_data_save" should be created. It include "accel_map.csv"", "brake_map.csv" and "graph.svg".

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [x] Code follows [coding guidelines][coding-guidelines]
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code follows [coding guidelines][coding-guidelines]
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR / build-and-test-pr**: Required to pass before the merge.
- **Build and test for PR / clang-tidy-pr**: NOT required to pass before the merge. It is up to the reviewer(s).
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[coding-guidelines]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/1194394777/T4
[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

### CODE REVIEW

**Comment by yabuta** [comment]
@TakumiKozaka-T4 Please add api name to description.

**Comment by TakumiKozaka-T4** [comment]
I added api name and brief summary.

**Comment by yabuta** [comment]
@TakumiKozaka-T4 Cc: @isamu-takagi 
Do you add this api to document?

**Comment by TakumiKozaka-T4** [comment]
@yabuta 
Not yet. I'll add this later.

**Comment by TakumiKozaka-T4** [comment]
Fixed review procedure for calibration status.
(Changed topic name from "/accel_brake_map_calibrator/output/calibration_status" to "/api/external/get/calibration_status")

**Review by yabuta — APPROVED** [review]
LGTM

**Pull request merged**
